name: substitute_content

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  create:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Subtitute_README
        run: |
          repo=$(basename `git rev-parse --show-toplevel`)
          sed -i "s/smk-template/$repo/g" README.md

      - name: Subtitute_LICENSE
        run: |
          year=`date +"%Y"`
          sed -i "s/2023/$year/g" LICENSE

      - name: Commit files
        run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add README.md LICENSE
           git commit -m "Substitute repo name on the README.md and year on the LICENSE"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
